print("Max number from [7, 5, 6, 3, 8, 22] is ", max([7, 5, 6, 3, 8, 22]))
print("Binary representation of a number 304 is",  bin(304))
print("Hexadecimal representation of a number 304 is ", hex(304))
print("ASCII number of character € is ", ord('€'))
print("Absolute value of number -17 is ",abs(-17))